# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: NextMove
subtitle: Neste generasjon grensesnitt

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/move-api'

# Author/Organization info to be displayed in the templates
author:
  name: Difi
  url: http://www.difi.no

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: https://www.difi.no/_style/design/difi3/img/difi-logo-small-bw.png 
logoalt: Difi

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Heim
  url: ./
  internal: true
- text: Bakgrunn
  url: bakgrunn/
  internal: true
- text: Grensesnitt
  url: grensesnitt/
  internal: true
- text: Swagger
  url: swagger/
  internal: true
- text: Move API Repo
  url: https://github.com/difi/move-api
  internal: false

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: MOVE
  description: Meldingsutveksling
  url: https://github.com/difi/move-integrasjonspunkt
- name: MOVE API
  description: Meldingsutveksling API
  url: https://github.com/difi/move-api

# Style Variables
brand_color: "#2cb34a"

# Offline caching
offline_cache: false
cache_name: DOCter-v1.1
